services:
  fretlog:

    image: ghcr.io/affekopp/fretlog:main
    container_name: fretlog
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_PATH=/app/data/fretlog.db
    volumes:
      - ./data:/app/data
